export interface Product {
  id: number;
  name: string;
  description: string;
  serves: string;
  price: number;
  image: string;
}

export const products: Product[] = [
  {
    id: 1,
    name: "Bolo Caseiro Vulcão - Delícia de Morango",
    description: "Massa branca, geleia de morango artesanal, brigadeiro branco e morangos in-natura.",
    serves: "Serve 1 a 2 pessoas (aprox. 400g).",
    price: 21.90,
    image: "/caseirinho-morango.jpg",
  },
  {
    id: 2,
    name: "Bolo Caseiro Vulcão - Sensação",
    description: "Massa de chocolate, geleia de morango artesanal, brigadeiro de chocolate, fios de creme de avelã e morangos in-natura.",
    serves: "Serve 1 a 2 pessoas (aprox. 400g).",
    price: 21.90,
    image: "/caseirinho-sensacao.jpg",
  },
  {
    id: 3,
    name: "Bolo Caseiro Vulcão - Chocolatudo",
    description: "Massa chocolate, brigadeiro de chocolate e pedaços de Brownie.",
    serves: "Serve 1 a 2 pessoas (aprox. 400g).",
    price: 18.90,
    image: "/caseirinho-brownie.jpg",
  },
  {
    id: 4,
    name: "Bolo Caseiro Vulcão - Choco-Ninho",
    description: "Massa chocolate, brigadeiro branco, Ninho e bombom.",
    serves: "Serve 1 a 2 pessoas (aprox. 400g).",
    price: 18.90,
    image: "/caseirinho-choco-ninho.jpg",
  },
  {
    id: 5,
    name: "Bolo Caseiro Vulcão -Kit Kat",
    description: "Massa branca, brigadeiro branco e pedaços de Kit Kat.",
    serves: "Serve 1 a 2 pessoas (aprox. 400g).",
    price: 20.90,
    image: "/caseirinho-kitkat.jpg",
  },
  {
    id: 6,
    name: "Bolo Caseiro Vulcão - Ninho com Creme de Avelã",
    description: "Massa branca, brigadeiro de creme de avelã, brigadeiro branco e fios de creme de avelã.",
    serves: "Serve 1 a 2 pessoas (aprox. 400g).",
    price: 21.50,
    image: "/caseirinho-ninho-avela.jpg",
  },
  /*{
    id: 7,
    name: "Bolo no Pote - Delícia de Morango",
    description: "Camadas de massa branca, geleia de morango artesanal, brigadeiro branco e mousse de Ninho.",
    serves: "Serve 1 pessoa (aprox. 200g).",
    price: 13.90,
    image: "/pote-morango.jpg",
  },*/
  {
    id: 8,
    name: "Bolo no Pote - Choco-Ninho",
    description: "Camadas de massa de chocolate, brigadeiro branco, Ninho e mousse de Ninho.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 13.90,
    image: "/pote-choco-ninho.jpg",
  },
  {
    id: 9,
    name: "Bolo no Pote - Chocolatudo",
    description: "Camadas de massa de chocolate, brigadeiro de chocolate e mousse de chocolate.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 13.90,
    image: "/pote-chocolatudo.jpg",
  },
  {
    id: 10,
    name: "Bolo no Pote - Ouro Branco",
    description: "Camadas de massa branca, brigadeiro branco, mousse de Ninho e Ouro Branco em pedaços.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 15.90,
    image: "/pote-ouro-branco.jpg",
  },
  {
    id: 12,
    name: "Bolo no Pote - Prestígio",
    description: "Camadas de massa de chocolate, brigadeiro branco e de chocolate, mousse de chocolate e coco ralado.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 13.90,
    image: "/pote-prestigio.jpg",
  },
  {
    id: 13,
    name: "Bolo Gelado - Abacaxi com coco",
    description: "Massa branca, brigadeiro de coco, doce de abacaxi e coco ralado.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 11.90,
    image: "/gelado-abacaxi-coco.jpg",
  },
  {
    id: 14,
    name: "Bolo Gelado - Limão",
    description: "Massa branca, brigadeiro de limão, biscoito de limão e raspas de limão.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 11.50,
    image: "/gelado-limao.jpg",
  },
  {
    id: 15,
    name: "Bolo Gelado - Prestígio",
    description: "Massa de chocolate, brigadeiro de coco, brigadeiro de chocolate e coco ralado.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 10.50,
    image: "/gelado-prestigio.jpg",
  },
  {
    id: 16,
    name: "Bolo Gelado - Amendoim com Creme de Avelã",
    description: "Massa de chocolate, brigadeiro de creme de avelã, brigadeiro de chocolate, amendoim granulado e fios de creme de avelã.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 11.90,
    image: "/gelado-avela-amendoim.jpg",
  },
  {
    id: 17,
    name: "Bolo Gelado - DuoChoco",
    description: "Massa de chocolate, brigadeiro branco e brigadeiro de chocolate.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 10.90,
    image: "/gelado-duo-choco.jpg",
  },
  {
    id: 18,
    name: "Brownie - Brownie Recheado de Ninho",
    description: "Brownie que desmancha na boca, recheado com brigadeiro de Ninho.",
    serves: "Serve 1 pessoa (aprox. 130g).",
    price: 7.90,
    image: "/brownie-ninho.jpg",
  },
  {
    id: 19,
    name: "Brownie Recheado de Doce de Leite",
    description: "Brownie que desmancha na boca, recheado com doce de leite.",
    serves: "Serve 1 pessoa (aprox. 130g).",
    price: 7.90,
    image: "/brownie-doceleite.jpg",
  },
  {
    id: 20,
    name: "Brownie Recheado de Brigadeiro",
    description: "Brownie que desmancha na boca, recheado com brigadeiro de chocolate.",
    serves: "Serve 1 pessoa (aprox. 130g).",
    price: 7.90,
    image: "/brownie-brigadeiro.jpg",
  },
  /*{
    id: 21,
    name: "Brownie no Pote - Bombom de Morango",
    description: "Camadas de mousse de Ninho e mousse de chocolate, brigadeiro de chocolate e brigadeiro branco, morangos frescos e lasquinhas de Brownie.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 11.50,
    image: "/caseirinho-morango.jpg",
  },
  {
    id: 22,
    name: "Brownie no Pote - Duo Choco",
    description: "Camadas de mousse de Ninho e mousse de chocolate, brigadeiro de chocolate e brigadeiro branco e lasquinhas de Brownie.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 11.50,
    image: "/caseirinho-morango.jpg",
  },*/
  {
    id: 23,
    name: "Afogadaço de Brownie - Ninho com Avelã",
    description: "Brownie coberto com brigadeiro branco, Ninho e fios de creme de avelã.",
    serves: "Serve 1 pessoa (aprox. 230g).",
    price: 11.90,
    image: "/afogadaco-ninho-avela.jpg",
  },
  /*{
    id: 24,
    name: "Afogadaço de Brownie - Floresta Negra",
    description: "Brownie coberto com brigadeiro de chocolate, geleia de morango e fios de creme de avelã.",
    serves: "Serve 1 pessoa (aprox. 200g).",
    price: 11.90,
    image: "/caseirinho-morango.jpg",
  },
  {
    id: 25,
    name: "Fatia de Brownie - Duo Kit Kat",
    description: "Fatia de Brownie coberto com brigadeiro de chocolate e brigadeiro branco, fios de creme de avelã e Kit Kat.",
    serves: "Serve 1 pessoa (aprox. 200g).",
    price: 11.50,
    image: "/fatia-kitkat.jpg",
  },
  {
    id: 26,
    name: "Fatia de Brownie - Morangos com Avelã",
    description: "Fatia de Brownie coberto com brigadeiro branco, fios de creme de avelã e morangos frescos.",
    serves: "Serve 1 pessoa (aprox. 200g).",
    price: 11.50,
    image: "/fatia-kitkat.jpg",
  },*/
];
