export interface Product {
  id: number;
  name: string;
  description: string;
  serves: string;
  price: number;
  image: string;
  category: string;
}

export const products: Product[] = [
  {
    id: 1,
    name: "Pizza de Brownie - Tentação",
    description: "Fatia de brownie, coberta com brigadeiro branco cremoso, fios de creme de avelã e morangos frescos.",
    serves: "Serve 1 pessoa (aprox. 150g).",
    price: 15.90,
    image: "/pizza-tentacao.jpeg",
    category: "Brownies",
  },
  {
    id: 2,
    name: "Pizza de Brownie - Amendoim com Avelã",
    description: "Fatia de brownie, coberta com brigadeiro de chocolate cremoso, fios de creme de avelã e amendoim granulado.",
    serves: "Serve 1 pessoa (aprox. 150g).",
    price: 15.90,
    image: "/pizza-amendoim.jpeg",
    category: "Brownies",
  },
  {
    id: 3,
    name: "Pizza de Brownie - Duo Kinder Bueno",
    description: "Fatia de brownie, coberta com brigadeiro branco e de chocolate cremoso, fios de creme de avelã e kinder bueno.",
    serves: "Serve 1 pessoa (aprox. 150g).",
    price: 15.90,
    image: "/pizza-kinder.jpeg",
    category: "Brownies",
  },
  {
    id: 7,
    name: "Trio Brownie",
    description: "Três fatias de brownie (5x5), coberto com brigadeiro cremoso, Brigadeiro Ninho, Brigadeiro de doce de leite e Duo Choco com Creme de Avelã.",
    serves: "Serve 1 pessoa (aprox. 130g).",
    price: 10.90,
    image: "/trio-brownie.jpeg",
    category: "Brownies",
  },
  {
    id: 11,
    name: "Brownie no Pote - Bombom de Morango",
    description: "Camadas de brigadeiro de chocolate e brigadeiro branco, morangos frescos e lasquinhas de Brownie.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 14.90,
    image: "/brownie-pote-morango.jpeg",
    category: "Brownies",
  },
  {
    id: 12,
    name: "Brownie no Pote - Duo Choco",
    description: "Camadas de brigadeiro de chocolate, brigadeiro branco e lasquinhas de Brownie.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 12.90,
    image: "/brownie-pote-choco.jpeg",
    category: "Brownies",
  },
   {
    id: 25,
    name: "Brownie no Pote - Tipo Ferrero",
    description: "Camadas de brigadeiro de chocolate, creme de avelã, amendoim e lasquinhas de Brownie.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 13.90,
    image: "/brownie-pote-ferrero.jpeg",
    category: "Brownies",
  },
  {
    id: 8,
    name: "Cookie Recheado",
    description: "Crocante por fora e macio por dentro, acompanha gotinhas de chocolate ao assar deixando muito mais saboroso. Assado na hora!",
    serves: "Serve 1 pessoa (aprox. 130g).",
    price: 8.90,
    image: "/coockie-recheado.jpeg",
    category: "Cookies",
  },
  {
    id: 9,
    name: "Turbinado de Cookie",
    description: "Composto por 6 cookies tradicionais com massa artesanal amanteigada, gotinhas de chocolate, com 1 pote de 50g de brigadeiro cremoso à sua escolha.",
    serves: "Serve 1 pessoa (aprox. 130g).",
    price: 13.90,
    image: "/cookie-turbinado.jpeg",
    category: "Cookies",
  },
  {
    id: 10,
    name: "Brigadeiro de Colher",
    description: "Brigadeiro de colher extremamente cremoso! 50g de puro sabor e cremosidade, cuidado ao comprar pois você vai querer repetir!",
    serves: "Serve 1 pessoa (aprox. 50g).",
    price: 3.90,
    image: "/brigadeiro.jpeg",
    category: "Cookies",
  },
  {
    id: 15,
    name: "Bolo Gelado - Abacaxi com coco",
    description: "Massa branca, brigadeiro de coco, doce de abacaxi e coco flocado.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 11.90,
    image: "/gelado-abacaxi-coco.jpg",
    category: "Bolos Gelado",
  },
  {
    id: 16,
    name: "Bolo Gelado - Prestígio",
    description: "Massa de chocolate, brigadeiro de chocolate de coco e coco flocado.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 10.50,
    image: "/gelado-prestigio.png",
    category: "Bolos Gelado",
  },
  {
    id: 17,
    name: "Bolo Gelado - Ninho com Geléia Morango",
    description: "Massa branca, brigadeiro branco, Ninho e geléia de morango.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 11.90,
    image: "/gelado-ninho-morango.jpeg",
    category: "Bolos Gelado",
  },
  {
    id: 18,
    name: "Bolo Gelado - DuoChoco",
    description: "Massa de chocolate, brigadeiro branco e brigadeiro de chocolate.",
    serves: "Serve 1 pessoa (aprox. 220g).",
    price: 10.90,
    image: "/gelado-duo-choco.jpg",
    category: "Bolos Gelado",
  },
  {
    id: 19,
    name: "Bolo Caseiro Vulcão - Delícia de Morango",
    description: "Massa branca, geleia de morango artesanal, brigadeiro branco e morangos in-natura.",
    serves: "Serve 1 a 2 pessoas (aprox. 400g).",
    price: 21.90,
    image: "/caseirinho-morango.jpg",
    category: "Bolos Caseiro Vulcão",
  },
  {
    id: 20,
    name: "Bolo Caseiro Vulcão - Sensação",
    description: "Massa de chocolate, geleia de morango artesanal, brigadeiro de chocolate, fios de creme de avelã e morangos in-natura.",
    serves: "Serve 1 a 2 pessoas (aprox. 400g).",
    price: 21.90,
    image: "/caseirinho-sensacao.jpg",
    category: "Bolos Caseiro Vulcão",
  },
  {
    id: 21,
    name: "Bolo Caseiro Vulcão - Chocolatudo",
    description: "Massa chocolate, brigadeiro de chocolate e pedaços de Brownie.",
    serves: "Serve 1 a 2 pessoas (aprox. 400g).",
    price: 18.90,
    image: "/caseirinho-brownie.jpg",
    category: "Bolos Caseiro Vulcão",
  },
  {
    id: 22,
    name: "Bolo Caseiro Vulcão - Choco-Ninho",
    description: "Massa chocolate, brigadeiro branco, Ninho e bombom.",
    serves: "Serve 1 a 2 pessoas (aprox. 400g).",
    price: 18.90,
    image: "/caseirinho-choco-ninho.jpg",
    category: "Bolos Caseiro Vulcão",
  },
  {
    id: 23,
    name: "Bolo Caseiro Vulcão -Kit Kat",
    description: "Massa branca, brigadeiro branco e pedaços de Kit Kat.",
    serves: "Serve 1 a 2 pessoas (aprox. 400g).",
    price: 20.90,
    image: "/caseirinho-kitkat.jpg",
    category: "Bolos Caseiro Vulcão",
  },
  {
    id: 24,
    name: "Bolo Caseiro Vulcão - Ninho com Creme de Avelã",
    description: "Massa branca, brigadeiro de creme de avelã, brigadeiro branco e fios de creme de avelã.",
    serves: "Serve 1 a 2 pessoas (aprox. 400g).",
    price: 21.50,
    image: "/caseirinho-ninho-avela.jpg",
    category: "Bolos Caseiro Vulcão",
  },
];
